//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GoodsTable
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public GoodsTable()
        {
            this.CommentTable = new HashSet<CommentTable>();
            this.GoodsPhoto = new HashSet<GoodsPhoto>();
            this.OrderTable = new HashSet<OrderTable>();
            this.ShoppingCartTable = new HashSet<ShoppingCartTable>();
            this.CollectionTable = new HashSet<CollectionTable>();
        }
    
        public int GoodsID { get; set; }
        public string GoodsName { get; set; }
        public decimal GoodsPrice { get; set; }
        public decimal OldGoodsPrice { get; set; }
        public int GoodsInventory { get; set; }
        public Nullable<int> TID { get; set; }
        public string GoodsDescribe { get; set; }
        public Nullable<int> GoodsStar { get; set; }
        public Nullable<int> GoodsHot { get; set; }
        public Nullable<int> IsDelte { get; set; }
        public Nullable<int> IsGet { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CommentTable> CommentTable { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GoodsPhoto> GoodsPhoto { get; set; }
        public virtual TypeTable TypeTable { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderTable> OrderTable { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ShoppingCartTable> ShoppingCartTable { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CollectionTable> CollectionTable { get; set; }
    }
}
