//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class LgShopDBEntities : DbContext
    {
        public LgShopDBEntities()
            : base("name=LgShopDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CommentTable> CommentTable { get; set; }
        public virtual DbSet<FeedbackTable> FeedbackTable { get; set; }
        public virtual DbSet<GoodsPhoto> GoodsPhoto { get; set; }
        public virtual DbSet<GoodsTable> GoodsTable { get; set; }
        public virtual DbSet<OrderTable> OrderTable { get; set; }
        public virtual DbSet<ShoppingCartTable> ShoppingCartTable { get; set; }
        public virtual DbSet<TypeTable> TypeTable { get; set; }
        public virtual DbSet<UserInfo> UserInfo { get; set; }
        public virtual DbSet<CollectionTable> CollectionTable { get; set; }
        public virtual DbSet<NoticeTable> NoticeTable { get; set; }
    }
}
