//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderTable
    {
        public int OrderID { get; set; }
        public Nullable<int> UserID { get; set; }
        public Nullable<int> GoodsID { get; set; }
        public Nullable<int> GoodsNum { get; set; }
        public Nullable<System.DateTime> GetTime { get; set; }
        public Nullable<decimal> OrderAmount { get; set; }
        public Nullable<int> IsReceiving { get; set; }
        public Nullable<int> IsComment { get; set; }
    
        public virtual GoodsTable GoodsTable { get; set; }
        public virtual UserInfo UserInfo { get; set; }
    }
}
