//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserInfo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public UserInfo()
        {
            this.CommentTable = new HashSet<CommentTable>();
            this.FeedbackTable = new HashSet<FeedbackTable>();
            this.OrderTable = new HashSet<OrderTable>();
            this.ShoppingCartTable = new HashSet<ShoppingCartTable>();
            this.CollectionTable = new HashSet<CollectionTable>();
            this.NoticeTable = new HashSet<NoticeTable>();
        }
    
        public int UserID { get; set; }
        public string UserName { get; set; }
        public string UserAccount { get; set; }
        public string UserPassword { get; set; }
        public string UserPhoto { get; set; }
        public string UserSex { get; set; }
        public int UserAge { get; set; }
        public string UserEmail { get; set; }
        public string UserPhont { get; set; }
        public string UserCard { get; set; }
        public System.DateTime UserBirthdays { get; set; }
        public Nullable<decimal> UserWallet { get; set; }
        public string CoverPhoto { get; set; }
        public string ReceivingAddress { get; set; }
        public Nullable<int> IsDelte { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CommentTable> CommentTable { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FeedbackTable> FeedbackTable { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderTable> OrderTable { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ShoppingCartTable> ShoppingCartTable { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CollectionTable> CollectionTable { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NoticeTable> NoticeTable { get; set; }
    }
}
